name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: "3.1"
      - name: bundle
        uses: actions/upload-artifact@v2
        run: |
          bundle
          ruby options.rb > params.json
      - name: artifacts
        with:
          name: params.json
          path: params.json
          retention-days: 3
